### ISSUE TITLE
Code for generating candidate entities during evaluation for WikiKG

### ISSUE THREAD

**Issue by chocolate9624** [google-research/smore#5]
Hi, I noticed the evaluation data is loaded in this line https://github.com/google-research/smore/blob/5b1a8a00b0cbfa024f411fc080b3d46dc681edd8/smore/training/main_train.py#L212 for WikiKG. 

However, I cannot find the code for generating candidate tail entities during evaluation. Can you show more details?

Thanks a lot!

**Comment by hyren** [comment]
Hi, I have updated the preprocess code to download the candidate set. Please check [here](https://github.com/google-research/smore/commit/96b6d1693f408f0ca45c9b74d7822f0716a3af7e).

**Comment by LeoYML** [comment]
Could you give more details about how to generate the candidates of valid data?

valid_url = "https://snap.stanford.edu/smore/valid.pt"
I see the comments in code: "# Specifically designed for OGB-LSC WikiKG v2. Since no candidates are provided by the original dataset, we generate candidates based on heuristics such as degrees / entity types."
But I can't reproduce this, and the candidates of per relation is difference(about < 1%).

In my opinion, the logistic is    train_data.groupby('relation')['tail'].apply(lambda grp: list(grp.value_counts().nlargest(20000).index))
right?
